---
- hosts: all
  tasks:
  
    - name: Telnet Client
      win_dsc:
        resource_name: WindowsFeature
        Name: 'Telnet-Client'
        Ensure: 'Present'

    - name: Microsoft Office 365 ClickToRun
      win_dsc: 
        resource_name: Package
        Name : 'MicrosoftOffice'
        Path : '\\sccm.xen.local\sources\Packages\MS\O365\SAC\setup.exe'
        ProductId : '90160000-008C-0000-1000-0000000FF1CE'
        Ensure :  'Present'    
        Arguments : '/configure configuration.xml'
