---

- name: Test Playbook
  hosts: win 
  gather_facts: false

  tasks:
    - name: Install Windows Optional feature TelnetClient
      ansible.windows.win_dsc:
        resource_name: WindowsOptionalFeature
        Name: "TelnetClient"
        Ensure: "Enable"

    - name: Microsoft OneDrive - Production Ring
      win_dsc: 
        resource_name: Package 
        Ensure : 'Present'
        Path : '\\server01.corp.virtualbyte.nl\Sources\Packages\Evergreen\Microsoft OneDrive\OneDriveSetup-Production_AMD64.exe'
        Name : 'Microsoft OneDrive'
        ProductId : '' 
        Arguments : '/ALLUSERS /silent'

    - name: Microsoft Teams Machine-Wide Installer  
      win_dsc: 
        resource_name: Package 
        Ensure : 'Present'
        Path : '\\server01.corp.virtualbyte.nl\Sources\Packages\Evergreen\Microsoft Teams Machine Based\Teams_x64_General.msi'
        Name : 'Teams Machine-Wide Installer'
        ProductId : '{731F6BAA-A986-45A4-8936-7C3AAAAA760B}' 
        Arguments : 'REBOOT=ReallySuppress ALLUSER=1 ALLUSERS=1 OPTIONS="noAutoStart=true" /qn'
  
    - name: Microsoft FSLogix
      win_dsc: 
        resource_name: Package 
        Ensure : 'Present'
        Path : '\\server01.corp.virtualbyte.nl\Sources\Packages\Evergreen\Microsoft FSLogix\Production\FSLogixAppsSetup.exe'
        Name : 'Microsoft FSLogix Apps'
        ProductId : '' 
        Arguments : '/install /norestart /quiet'

    - name: NotePadPlusPlus_x64 
      win_dsc: 
        resource_name: Package
        Ensure : 'Present'
        Path : '\\server01.corp.virtualbyte.nl\Sources\Packages\Evergreen\NotePadPlusPlus\NotePadPlusPlus_x64.exe'
        Name : 'Notepad++ (64-bit x64)'
        ProductId : '' 
        Arguments : '/S'

    - name: Google Chrome 
      win_dsc: 
        resource_name: Package 
        Ensure : 'Present'
        Path : '\\server01.corp.virtualbyte.nl\Sources\Packages\Evergreen\Google Chrome\googlechromestandaloneenterprise_x64.msi'
        Name : 'Google Chrome'
        ProductId : '{32490FC2-5E1B-3CB2-9D0C-3FA41E9439E9}' 
        Arguments : '/qn'

    - name: Adobe Reader DC
      win_dsc: 
        resource_name: Package 
        Ensure : 'Present'
        Path : '\\server01.corp.virtualbyte.nl\Sources\Packages\Evergreen\Adobe Reader DC\Adobe_Reader_DC_x64English.exe'
        Name : 'Adobe Acrobat DC (64-bit)'
        ProductId : '' 
        Arguments : '/sAll /rs /msi EULA_ACCEPT=YES ENABLE_OPTIMIZATION=YES DISABLEDESKTOPSHORTCUT=1 UPDATE_MODE=0 DISABLE_ARM_SERVICE_INSTALL=1 DISABLE_CACHE=1 DISABLE_PDFMAKER=YES ALLUSERS=1'

#    - name: Reboot Action
#      win_reboot:
#        post_reboot_delay: 30